services:
  # L'application Symfony + Serveur Web (FrankenPHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valoricarcasse_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/app/Caddyfile
    environment:
      DATABASE_URL: "mysql://valori_user:valori_secure_password@db:3306/valori_carcasse?serverVersion=mariadb-10.11.0"
      APP_SECRET: "ChangerCeSecretEnProductionPourSecuriserLApp"
    depends_on:
      - db
    command: sh -c "php bin/console importmap:install && php bin/console asset-map:compile && php bin/console cache:warmup --env=prod && frankenphp run --config /etc/frankenphp/Caddyfile"

  # La Base de données (MariaDB)
  db:
    image: mariadb:10.11
    container_name: valoricarcasse_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: valori_carcasse
      MYSQL_USER: valori_user
      MYSQL_PASSWORD: valori_secure_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306" # Évite d'exposer la BDD publiquement sur internet

  # L'interface graphique pour la BDD (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: valoricarcasse_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: valori_user
      PMA_PASSWORD: valori_secure_password
      UPLOAD_LIMIT: 32M
    ports:
      - "8080:80"

volumes:
  caddy_data:
  caddy_config:
  mariadb_data:
